#!/usr/bin/env python3

import os
import sys
import urllib.request


ROOT = os.path.dirname(os.path.realpath(__file__))
VIEWER_FILE = os.path.join(ROOT, "index.html");
VIEWER_URL = "http://starkups.s.zeid.me/"

STATIC_NAME_PLACEHOLDER = b"__SKP"+b"_"+b"INSERT_NAME_HERE__"
STATIC_DATA_PLACEHOLDER = b"__SKP"+b"_"+b"INSERT_DATA_HERE__"


def get_viewer() -> bytes:
 html = b""
 if os.path.isfile(VIEWER_FILE):
  with open(VIEWER_FILE, "rb") as f:
   html = f.read()
 if STATIC_NAME_PLACEHOLDER in html and STATIC_DATA_PLACEHOLDER in html:
  return html
 else:
  html = urllib.request.urlopen(VIEWER_URL).read()
  if STATIC_NAME_PLACEHOLDER in html and STATIC_DATA_PLACEHOLDER in html:
   return html
  else:
   raise IOError("Downloaded viewer is not a valid Starkups viewer")


def html_escape_bytes(s: bytes, quote: bool = True) -> bytes:
 s = s.replace(b"&", b"&amp;")
 s = s.replace(b"<", b"&lt;")
 s = s.replace(b">", b"&gt;")
 if quote:
  s = s.replace(b"'", b"&#39;")
  s = s.replace(b'"', b"&quot;")
 return s


def prepare(skp: bytes, name: str = "untitled.skp") -> bytes:
 name = os.path.basename(name)
 
 try:
  html = get_viewer()
 except IOError as exc:
  raise IOError(f"error loading the viewer: {exc}")
 
 html = html.replace(STATIC_NAME_PLACEHOLDER, html_escape_bytes(name.encode("utf-8")))
 html = html.replace(STATIC_DATA_PLACEHOLDER, html_escape_bytes(skp, False))
 
 return html


def main(argv: list[str]) -> int:
 prog = os.path.basename(argv[0])
 
 if len(argv) < 2:
  print(f"Usage: {prog} <filename|->", file=sys.stderr)
  return 2
 
 path = name = argv[1]
 if path == "-":
  skp = sys.stdin.buffer.read()
 else:
  name = os.path.basename(path)
  with open(path, "rb") as f:
   skp = f.read()
 
 try:
  html = prepare(skp, name)
 except IOError as exc:
  print(f"error: {exc}", file=sys.stderr)
  return 1
 
 sys.stdout.buffer.write(html)
 return 0


if __name__ == "__main__":
 try:
  sys.exit(main(sys.argv))
 except KeyboardInterrupt:
  pass
