#!/usr/bin/env python2

import os
import sys
import urllib2


ROOT = os.path.dirname(os.path.realpath(__file__))
VIEWER_FILE = os.path.join(ROOT, "index.html");
VIEWER_URL = "http://starkups.s.zeid.me/"

STATIC_NAME_PLACEHOLDER = "__SKP"+"_"+"INSERT_NAME_HERE__"
STATIC_DATA_PLACEHOLDER = "__SKP"+"_"+"INSERT_DATA_HERE__"


def get_viewer():
 html = ""
 if os.path.isfile(VIEWER_FILE):
  with open(VIEWER_FILE, "rb") as f:
   html = f.read()
 if STATIC_NAME_PLACEHOLDER in html and STATIC_DATA_PLACEHOLDER in html:
  return html
 else:
  html = urllib2.urlopen(VIEWER_URL).read()
  if STATIC_NAME_PLACEHOLDER in html and STATIC_DATA_PLACEHOLDER in html:
   return html
  else:
   raise IOError("Downloaded viewer is not a valid Starkups viewer")


def html_escape(s, quote=True):
 s = s.replace("&", "&amp;")
 s = s.replace("<", "&lt;")
 s = s.replace(">", "&gt;")
 if quote:
  s = s.replace("'", "&#39;")
  s = s.replace('"', "&quot;")
 return s


def prepare(skp, name="untitled.skp"):
 name = os.path.basename(name)
 
 try:
  html = get_viewer()
 except IOError as exc:
  raise IOError("error loading the viewer: " + str(exc))
 
 html = html.replace(STATIC_NAME_PLACEHOLDER, html_escape(name))
 html = html.replace(STATIC_DATA_PLACEHOLDER, html_escape(skp, False))
 
 return html


def main(argv):
 if len(argv) < 2:
  print >> sys.stderr, "Usage: %s <filename|->" % argv[0]
  return 2
 
 path = name = argv[1]
 if path == "-":
  skp = sys.stdin.read()
 else:
  name = os.path.basename(path)
  with open(path, "rb") as f:
   skp = f.read()
 
 try:
  html = prepare(skp, name)
 except IOError as exc:
  print >> sys.stderr, str(exc)
  return 1
 
 sys.stdout.write(html)


if __name__ == "__main__":
 try:
  sys.exit(main(sys.argv))
 except KeyboardInterrupt:
  pass
